### PR TITLE
Switch to using aac for audio for compatability with quicktime player

### PR DESCRIPTION
**Pull request by hammertoe**
Sean, switching to aac in order to work better on Quicktime. Any downsides you know of?

### CODE REVIEW

**Comment by seanmtracey** [comment]
Golly, this got right past me.

I'm inclined to say that seeing as we've gotten this far without it, we should probably leave it as it is. IIRC (and bear in mind, I haven't thought about this since last June) there were some incompatibilities with certain browsers if we did introduce AAC.

What do we think?

**Comment by glynnbird** [comment]
As it happens, we used stitcheroo in the early days of choirless but it is
now not used and replaced by the serverless pipeline. I think this repo is
still useful for renders of smaller jobs , say < 30 videos

**Comment by krook** [comment]
Based on the conversation above, do you think we should close this @glynnbird @hammertoe?

**Review by seanmtracey — APPROVED** [review]
LGTM 👍

**Comment by krook** [comment]
Sorry, do you mean close this or merge this @seanmtracey?

**Comment by seanmtracey** [comment]
Merge away 🚀

**Pull request merged**
